hashicorp/terraform-plugin-testing

- go.mod
- go.sum
- helper/resource/testing_new_config_test.go
- helper/resource/testing_new_import_state_test.go
- helper/resource/wait_test.go
A recent update of `tfexec`[v0.18.0](https://github.com/hashicorp/terraform-exec/releases/tag/v0.18.0) caused a regression where detailed stderr information wasn't being passed to this testing module. This has now been fixed with the new release [v0.18.1](https://github.com/hashicorp/terraform-exec/releases/tag/v0.18.1)
- Added tests for ExpectError, so future CI can catch bugs similar to the one introduced in #58 
- I'm not sure how to cause the `terraform refresh` command to fail, so I left that test out for now
- Example of new tests [failing](https://github.com/hashicorp/terraform-plugin-testing/actions/runs/4304174942/jobs/7504818466#step:5:8) w/ tfexec `v0.18.0`
- Upgrading tfexec to `v0.18.1` to fix bug of error not containing stderr information: …
> Upgrade tfexec to `v0.18.1` + add tests for `ExpectError`

- helper/acctest/random.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/issues/621
Similar to `RandSSHKeyPair`, whose cryptographic characteristics were recently more documented, the `RandTLSCert` helper was created with limited customization capabilities. Security requirements are constantly evolving and it is untenable for this Go module to maintain all possible permutations required for cryptographic logic needed across the entire provider ecosystem without constant maintenance or inevitably needing to introduce breaking changes to the exported Go APIs. Future major versions of this code would likely remove helpers like these for that reason, but any decision in that regard would happen at a later date. For now, this documentation will encourage developers to create their own functionality using …
> helper/acctest: Further document RandTLSCert characteristics

- .goreleaser.yml
Goreleaser deprecated the `build` field as it was previously not a documented field. Replaced with the equivalent `builds` array per deprecation guide: https://goreleaser.com/deprecations/#build
Failures seen in:
- https://github.com/hashicorp/terraform-plugin-testing/pull/101
- https://github.com/hashicorp/terraform-plugin-testing/pull/100
> Fix goreleaser deprecated `build` field

- helper/resource/testing.go
Successful and unsuccessful sweeper names are currently written to stdout instead of the logger, while other output goes to the logger. This PR updates the output destination to be the logger
> Logs successful and unsuccessful sweeper names instead of writing to stdout

- .changes/unreleased/FEATURES-20230720-163447.yaml
- .changes/unreleased/FEATURES-20230720-163627.yaml
- .changes/unreleased/FEATURES-20230720-163828.yaml
- plancheck/expect_sensitive_value.go
- plancheck/expect_sensitive_value_test.go
- plancheck/expect_unknown_value.go
- plancheck/expect_unknown_value_test.go
- tfjsonpath/doc.go
- tfjsonpath/path.go
- tfjsonpath/path_test.go
- tfjsonpath/step.go
- website/data/plugin-testing-nav-data.json
- website/docs/plugin/testing/acceptance-tests/plan-checks.mdx
- website/docs/plugin/testing/acceptance-tests/tfjson-paths.mdx
This PR implements the design described in [[TF-727](https://hermes.hashicorp.services/document/1EISBQ5PDYPfCQq_VxRW2xb15Sic1LitfHTWAqz1IYKY)] Terraform Plugin Testing Sensitive and Unknown Plan Checks and adds the following:
- `tfjsonpath` package which defines methods that allows provider developers to traverse Terraform JSON data
- `ExpectUnknownValue()` plan check which asserts that the specified attribute is unknown in the plan
- `ExpectSensitiveValue()` plan check which asserts that the specified attribute is marked sensitive in the plan
[TF-727]: https://hashicorp.atlassian.net/browse/TF-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Introduce `tfjsonpath` Package and Sensitive and Unknown Plan Checks

- helper/resource/teststep_providers_test.go
- internal/testing/doc.go
- internal/testing/testprovider/datasource.go
- internal/testing/testprovider/doc.go
- internal/testing/testprovider/provider.go
- internal/testing/testprovider/resource.go
- internal/testing/testsdk/datasource/datasource.go
- internal/testing/testsdk/datasource/doc.go
- internal/testing/testsdk/doc.go
- internal/testing/testsdk/provider/doc.go
- internal/testing/testsdk/provider/provider.go
- internal/testing/testsdk/providerserver/datasources.go
- internal/testing/testsdk/providerserver/doc.go
- internal/testing/testsdk/providerserver/providerserver.go
- internal/testing/testsdk/providerserver/resources.go
- internal/testing/testsdk/providerserver/schema.go
- internal/testing/testsdk/providerserver/tftypes.go
- internal/testing/testsdk/resource/doc.go
- internal/testing/testsdk/resource/resource.go
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/151
Creates an internal terraform-plugin-go based SDK and declarative provider for unit testing for within this Go module. The new `helper/resource` tests should be equivalent to the existing terraform-plugin-sdk based `TestTest_TestStep_ExternalProviders_To_ProviderFactories` and `TestTest_TestStep_ProviderFactories_To_ExternalProviders` tests.
> internal/testing: Initial testsdk and testprovider packages

- .changes/unreleased/ENHANCEMENTS-20230820-195300.yaml
- .changes/unreleased/FEATURES-20230820-195624.yaml
- helper/resource/state_shim.go
- helper/resource/testcase_test.go
- helper/resource/testing.go
- helper/resource/testing_new_import_state.go
- helper/resource/teststep_test.go
- internal/testing/testsdk/providerserver/providerserver.go
Closes #84
The resource instance state identifier was a Terraform versions 0.11 and earlier concept which helped core and the then SDK determine if the resource should be removed and as an identifier value in the human readable output. This concept unfortunately carried over to the testing logic when the testing logic was mostly changed to use the public, machine-readable JSON interface with Terraform, rather than reusing prior internal logic from Terraform. Using the `id` attribute value for this identifier was the default implementation and therefore those older versions of Terraform required the attribute. This is no longer necessary after Terraform versions 0.12 and later. This testing logic only supports Terraform version 0.12.26 and later.
The remaining resource instance identifier …
> helper/resource: Remove data source and resource `id` attribute requirement

- website/docs/plugin/testing/acceptance-tests/index.mdx
Reference: https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file
This prevents developers from needing to continually update their testing workflow with Go upgrades, which can be pointed at the minimum Go version as defined by their Go module.
> website: Update GitHub Actions example for setup-go@v4 and using go.mod version

- helper/resource/testing_new_config_test.go
- helper/resource/testing_new_import_state_test.go
- helper/resource/testing_new_refresh_state_test.go
- helper/resource/teststep_providers_test.go
Closes #151
This will reduce CI time and dependency on networking/registry calls. Other unit testing that can be refactored can be done when the terraform-plugin-sdk dependency is being removed.
> helper/resource: Refactor various unit testing to use inline providers

- helper/resource/state_shim.go
- helper/resource/testing.go
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
- helper/resource/testing_new_import_state.go
- helper/resource/testing_test.go
- terraform/diff.go
- terraform/resource.go
- terraform/resource_provider.go
- terraform/schemas.go
- terraform/state.go
Closes #165
Except in certain known provider testing use cases without replacement (yet), this deprecates various `terraform` package functionality. The `terraform` package contains legacy Terraform core logic which has been copied to terraform-plugin-sdk and terraform-plugin-testing over the years and continually exported due to the complexity of rewriting developer functionality using the machine-readable interfaces for Terraform, such as JSON state. Much of this now-deprecated `terraform` package logic should have been omitted when this Go module was created, but that step was missed, so it is left as-is with deprecation notices following the Go module versioning guidelines. In reality, the entire `terraform` package will be removed in a future major version, however this change …
> terraform: Add deprecation Go documentation comments

- .changes/unreleased/BUG FIXES-20230831-171932.yaml
- helper/resource/teststep_validate.go
- helper/resource/teststep_validate_test.go
Closes: #176 
Prior to the changes in this PR, the following test failed:
```go
"config-providers-testcase-providers": {
testStep: TestStep{
Config: "provider abc {",
},
testStepConfig: "# not empty",
testStepValidateRequest: testStepValidateRequest{
TestCaseHasProviders: true,
},
},
```
```shell
=== NAME  TestTestStepValidate/config-providers-testcase-providers
teststep_validate_test.go:523: unexpected error: Providers must only be specified either at the TestCase or TestStep level
```
Whereas the equivalent test in `v1.4.0` passes:
```go
"config-providers-testcase-providers": {
testStep: TestStep{
Config: "provider abc {",
},
testStepValidateRequest: testStepValidateRequest{
TestCaseHasProviders: true,
},
},
```
> Fix regression by allowing providers defined at `TestCase` level with providers defined within `TestStep.Config`

- helper/resource/testing.go
The documentation specified `-sweep-allow-failues` as one of the flags that could be passed.
This PR corrects the docs to specify `-sweep-allow-failures`.
> Fix typo in documentation for `-sweep-allow-failures` flag

- .github/workflows/ci-go.yml
- helper/resource/testcase_providers_test.go
- helper/resource/testcase_test.go
- helper/resource/testing_new_config_test.go
- helper/resource/testing_new_import_state_test.go
- helper/resource/testing_new_refresh_state_test.go
- helper/resource/teststep_providers_test.go
- helper/resource/teststep_test.go
- plancheck/expect_sensitive_value_test.go
- tfversion/all_test.go
- tfversion/any_test.go
- tfversion/require_above_test.go
- tfversion/require_below_test.go
- tfversion/require_between_test.go
- tfversion/require_not_test.go
- tfversion/skip_above_test.go
- tfversion/skip_below_test.go
- tfversion/skip_between_test.go
- tfversion/skip_if_test.go
This change adds Terraform version matrix testing to the Go code testing workflow and ensures that acceptance testing is enabled, since there are many tests that require the environment variable to run. Unsetting `TF_ACC_TERRAFORM_PATH` is necessary for locally running the tests on other Terraform versions.
> ci: Enable acceptance testing

- plancheck/expect_null_output_value_at_path_test.go
- plancheck/expect_unknown_output_value_at_path_test.go
- plancheck/expect_unknown_output_value_test.go
Recently, the `terraform-plugin-testing` module was updated to use a matrix of Terraform versions to use when running tests (refer to [ci: Enable acceptance testing](https://github.com/hashicorp/terraform-plugin-testing/pull/224#top)). This has uncovered two issues:
- Tests that use `terraform_data` fail, as the `terraform_data` resource is only available in Terraform `v1.4.0` and later versions (refer to [Enhancements](https://github.com/hashicorp/terraform/blob/v1.4/CHANGELOG.md#140-march-08-2023)).
- Tests that use a path within an output value fail if any attribute value within the resource is unknown, as the entire resource is then marked as unknown in Terraform versions prior to `v1.3.0` (refer to [Upgrade Notes](https://github.com/hashicorp/terraform/blob/v1.3/CHANGELOG.md#130-septe …
> Skip tests when resource unavailable or entire resource is marked unknown

- .changes/unreleased/ENHANCEMENTS-20231122-115402.yaml
- helper/resource/testing_new_config.go
- internal/plugintest/working_dir.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/pull/515
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/194
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/222
Reference: https://developer.hashicorp.com/terraform/cli/commands/refresh
This change replaces the usage of explicit refresh commands by instead calling the next command with the relevant refresh flags. Separating the refresh from plan was previously done with the idea that the testing logic may introduce further assertion hooks based on that explicit refresh. Over time though, the Terraform recommendations for refreshing and planning have solidified around always recommending to use a plan with behavior changing flags as necessary. Even the Terraform CLI implementation …
> helper/resource: Refresh during plan rather than separately and remove state shimming when possible

- tfversion/versions.go
Terraform 1.6 already exists and 1.7 is in alpha phase, so it will exist soon enough. This does not feel like it warrants a changelog entry for such as small change, but happy to create one.
> tfversion: Add variables for version 1.6.0 and 1.7.0

- .changes/unreleased/BUG FIXES-20231130-102326.yaml
- .changes/unreleased/NOTES-20231201-160257.yaml
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
- helper/resource/testing_new_config_test.go
- helper/resource/testing_new_refresh_state.go
- helper/resource/testing_new_refresh_state_test.go
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/222
This is a followup to similar `plancheck` implementation updates that ensure output changes are checked in the plan in addition to resource changes. The intention of this functionality is to catch any plan differences and has been documented in this manner for a long while.
Since `TestStep.ExpectNonEmptyPlan` pre-dates this Go module, for extra compatibility for developers migrating, output checking is only enabled for Terraform 0.14 and later since prior versions will always show changes when outputs are present in the configuration. Ideally `TestStep.ExpectNonEmptyPlan` will be deprecated in preference of the newer plan checks since its abstraction is fairly ambiguous to when its being invoked, but this …
> helper/resource: Ensure TestStep.ExpectNonEmptyPlan accounts for output changes

- helper/resource/testing.go
Sorry meant to include this with https://github.com/hashicorp/terraform-plugin-testing/pull/238
This is a quick followup recent clarification changes in error messages to better mention intended use and message compatibility with `TestCase.ErrorCheck` and `TestStep.ExpectError`.
> helper/resource: Go documentation intentions for ErrorCheck and ExpectError

- website/docs/plugin/testing/migrating.mdx
These items came up during an official provider migration which:
- Implemented terraform-plugin-sdk based resource with state migrations and covering unit testing that needed to remain.
- Had not migrated `resource.Retry` to `resource.RetryContext` yet, so needed the extra entry
> website: Additional terraform.InstanceState and resource.Retry clarifications in migration guide

- .changes/1.6.0.md
- CHANGELOG.md
Reference: https://github.com/hashicorp/terraform-plugin-testing/pull/223
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/237
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/256
Post-release update to the v1.6.0 CHANGELOG to capture now-known situations that would affect existing provider testing. This update ensures developers upgrading to v1.6.0 will receive the latest guidance and the guidance will remain for this version after future releases. If approved and merged, the v1.6.0 GitHub Release description will also be updated with the same additional content.
> Additional CHANGELOG note for v1.6.0

- go.mod
- terraform/resource.go
- terraform/state.go
Reference: https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc
Its usage was only in esoteric functionality that is unintentionally exported and already deprecated. The `maps`/`slices` Go standard library packages are only Go 1.21+ so could not leverage that immediately since this Go module is 1.20+ until 1.22 is released, but the structures are small enough that its not too much lift to implement the manual copying code.
Remaining indirect dependency is via sdk/v2 (which that dependency will go away next major version anyways):
```
github.com/hashicorp/terraform-plugin-testing/helper/resource
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
github.com/mitchellh/copystructure
```
> deps: Remove direct dependency on github.com/mitchellh/copystructure

- go.mod
- terraform/resource.go
- terraform/resource_test.go
- terraform/state.go
- terraform/unknown_value_walk.go
- terraform/unknown_value_walk_test.go
Reference: https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc
Its usage was only in esoteric functionality that is unintentionally exported and already deprecated.
Remaining indirect dependency is via sdk/v2 (which that dependency will go away next major version):
```
github.com/hashicorp/terraform-plugin-testing/helper/resource
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
github.com/hashicorp/terraform-plugin-sdk/v2/terraform
github.com/mitchellh/reflectwalk
```
> deps: Remove direct dependency on github.com/mitchellh/reflectwalk

- config/constraints.go
- config/variable.go
- go.mod
- go.sum
Reference: https://github.com/golang/go/issues/61914
It was only used for the `constraints` package, the type definitions are relatively trivial and static, and the Go language maintainers are not sure if/where these will live in the standard library, which implies (at least to me) they could also disappear from x/exp.
> deps: Remove golang.org/x/exp dependency

- website/docs/plugin/testing/migrating.mdx
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/237
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/256
Technically, this testing change is always safe to make, but this calls out the currently known situations it will cause errors to not over-burden developers during their migration.
> website: Mention PlanOnly to ConfigPlanChecks in migration guide

- tfversion/versions.go
Terraform 1.7 is now generally available and we know there will be 1.8 for provider functions, etc. This does not feel like it warrants a changelog entry for such as small change, but happy to create one.
> tfversion: Add variable for version 1.8.0

- .changes/unreleased/BUG FIXES-20240229-095804.yaml
- helper/resource/testing_new.go
Adds missing calls to `t.Helper()` in two `defer`ed functions.
Closes https://github.com/hashicorp/terraform-plugin-testing/issues/292.
```console
% go test ./...
?   	github.com/hashicorp/terraform-plugin-testing/helper/logging	[no test files]
ok  	github.com/hashicorp/terraform-plugin-testing/config	2.009s
ok  	github.com/hashicorp/terraform-plugin-testing/helper/acctest	2.362s
?   	github.com/hashicorp/terraform-plugin-testing/internal/addrs	[no test files]
?   	github.com/hashicorp/terraform-plugin-testing/internal/testing	[no test files]
?   	github.com/hashicorp/terraform-plugin-testing/internal/testing/testprovider	[no test files]
?   	github.com/hashicorp/terraform-plugin-testing/internal/testing/testsdk	[no test files]
? …
```
> Add calls to `t.Helper()` in `defer`ed functions

- tfversion/versions.go
Terraform 1.8.0-beta1 has been released and a 1.9 release branch has already been cut with its own changelog entries so we know there will be 1.9 series. As with any of these `tfversion` version variable inclusions, it does not feel like it warrants a changelog entry for such as small change, but happy to create one.
> tfversion: Add variable for version 1.9.0

- .changes/unreleased/ENHANCEMENTS-20240325-120539.yaml
- knownvalue/list_partial_test.go
- knownvalue/tuple.go
- knownvalue/tuple_partial.go
- knownvalue/tuple_partial_test.go
- knownvalue/tuple_size.go
- knownvalue/tuple_size_test.go
- knownvalue/tuple_test.go
- website/data/plugin-testing-nav-data.json
- website/docs/plugin/testing/acceptance-tests/known-value-checks/custom.mdx
- website/docs/plugin/testing/acceptance-tests/known-value-checks/index.mdx
- website/docs/plugin/testing/acceptance-tests/known-value-checks/tuple.mdx
Closes #312
Exact copies of the `List*` equivalents.
I explicitly didn't add documentation, since these are only really useful for dynamic value testing, but I can add them if we think it's necessary 👍🏻
> knownvalue: Add `TupleExact`, `TuplePartial` and `TupleSizeExact` checks for dynamic value testing

- .changes/unreleased/ENHANCEMENTS-20240327-171628.yaml
- tfversion/skip_below.go
- tfversion/skip_below_test.go
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/303
Reference: https://github.com/hashicorp/terraform-plugin-testing/pull/308
This change is mainly due to the internals of how github.com/hashicorp/go-version treats version comparisons when there is prerelease data. When the running Terraform CLI is a prerelease version and the given version is a patch version, `SkipBelow` will currently skip the test. However, Terraform CLI prerelease versions are semantically treated as candidates for the associated patch version and therefore should be tested. This adjusts `SkipBelow` for that intended behavior. In the unexpected use case that prerelease version checking is still needed, callers can (still) opt into giving a prerelease version, which will perform the check …
> tfversion: Treat Terraform CLI prerelease versions as equal to patch versions in SkipBelow

- .changes/unreleased/ENHANCEMENTS-20240626-163240.yaml
- .changes/unreleased/ENHANCEMENTS-20240626-163311.yaml
- knownvalue/float32.go
- knownvalue/float32_test.go
- knownvalue/int32.go
- knownvalue/int32_test.go
- website/data/plugin-testing-nav-data.json
- website/docs/plugin/testing/acceptance-tests/known-value-checks/custom.mdx
- website/docs/plugin/testing/acceptance-tests/known-value-checks/float32.mdx
- website/docs/plugin/testing/acceptance-tests/known-value-checks/index.mdx
- website/docs/plugin/testing/acceptance-tests/known-value-checks/int32.mdx
- website/docs/plugin/testing/acceptance-tests/known-value-checks/int64.mdx
- website/docs/plugin/testing/acceptance-tests/tfjson-paths.mdx
Relates: https://github.com/hashicorp/terraform-plugin-framework/pull/1010
Relates: https://github.com/hashicorp/terraform-plugin-framework/pull/1014
Adds  `Int32Exact` and `Float32Exact` checks to the `knownvalue` package for `Int32` and `Float32` value testing respectively.
> knownvalue: Add `Int32Exact` and `Float32Exact` checks

- .changes/unreleased/NOTES-20240906-171054.yaml
- .github/workflows/ci-go.yml
- README.md
- go.mod
- tools/go.mod
Ref: https://github.com/hashicorp/terraform-providers-devex-internal/issues/182
Bumps the minimum Go module to 1.22.0 to allow for all patch versions in 1.22. Toolchain is using the latest 1.22.7
> all: Bump minimum Go module version to 1.22

- .changes/unreleased/FEATURES-20241108-160634.yaml
- helper/resource/testdata/TestTest_ConfigDirectory_TestNameDirectory_MultipleFiles_Vars/vars.tf
- plancheck/expect_deferred_change_test.go
- plancheck/expect_no_deferred_changes_test.go
- tfversion/skip_if_not_alpha.go
- tfversion/skip_if_not_alpha_test.go
Since we've recently added beta prereleases to our acceptance testing, we started getting test failures for experimental features like deferred actions that use the `SkipIfNotPrerelease` version check. That's because the only prerelease builds that get experimental features (like deferred actions) are `alpha` and source builds.
None of our CI uses source builds, so I just created a new `SkipIfNotAlpha` version check we can use for experimental features, while allowing `beta` builds to run in our CI successfully 👍🏻
> tfversion: Add `SkipIfNotAlpha` version check

- tfversion/versions.go
Terraform 1.11.0-beta1 will be releasing soon. We can come back and retroactively add a changelog if we don't have any `terraform-plugin-testing` releases upcoming (we don't typically add them for new version variables)
> tfversion: Add variable for version 1.11.0

- .changes/unreleased/ENHANCEMENTS-20250317-182730.yaml
- knownvalue/object.go
- knownvalue/object_test.go
Closes #451 
- I opted to just use a parenthetical plural in the error messages 😆
- There are likely plenty of other places where this logic should probably be used, but I wanted to close the most immediate issue report. We can tackle it in a similar way when we get follow-up issue requests.
> Add the missing/extra attribute names to the error message for `knownvalue.ObjectExact`

- .changes/unreleased/NOTES-20250325-084449.yaml
- helper/resource/plugin.go
- helper/resource/testing.go
- helper/resource/testing_new.go
This PR aims for visually-scannable debug output from tests.
It changes the detailed logging of the provider lifecycle in `resource.runProviderCommand` from DEBUG to TRACE level. I have used this patch locally for nearly a week. In one example, debug output improves [from 166 lines to 30 lines](https://gist.github.com/bbasata/72a70ed83ade2bb36d4db107a604e888).
The DEBUG-level logging originated 3 years ago in https://github.com/hashicorp/terraform-plugin-testing/commit/b5c80aa8ad22a69562d30e2e7d1ed56831b5aebf. I feel the provider lifecycle is stable enough that we can change it to TRACE logging. `resource.runProviderCommand` has logic to handle various provider errors by returning an `error`.
> Nice debug logs

- helper/resource/importstate/import_block_with_id_test.go
- helper/resource/testing_new_import_state.go
This change allows explict inline Terraform configuration in an `ImportState` test step. In a newly-added test, we have a scenario where it's useful to the test author to write their own import block, without resorting to `ConfigFile` or `ConfigDirectory`.
This change also adds a test to cover the use of external providers with plannable import tests.
> helper/resource: refine config-building for plannable import tests

- .changes/unreleased/ENHANCEMENTS-20250421-145039.yaml
- helper/resource/additional_cli_options.go
- helper/resource/testing_new_config.go
Closes https://github.com/hashicorp/terraform-plugin-testing/issues/489.
I see no value currently to adding the same to `ApplyOptions`.
> Add `AdditionalCLIOptions.PlanOptions.NoRefresh` to test `terraform plan -refresh=false`

- helper/resource/testing.go
Cross-ref b7440b30c2692d381fb938593cc9806ebbc58b8b
> Remove outdated comment

- .changes/unreleased/FEATURES-20250513-115526.yaml
- .changes/unreleased/FEATURES-20250514-095016.yaml
- internal/testing/testsdk/providerserver/providerserver.go
- statecheck/expect_identity_test.go
- statecheck/expect_identity_value_matches_state.go
- statecheck/expect_identity_value_matches_state_at_path.go
- statecheck/expect_identity_value_matches_state_at_path_example_test.go
- statecheck/expect_identity_value_matches_state_at_path_test.go
- statecheck/expect_identity_value_matches_state_example_test.go
- statecheck/expect_identity_value_matches_state_test.go
- statecheck/expect_identity_value_test.go
This PR adds two new state checks that asserts that an identity AND state value at the given path(s) are exactly equal. This was originally a suggestion from the Azure team that are looking to simplify their testing assertions.
cc @stephybun
> statecheck: Add new resource identity / state comparison checks

- helper/resource/importstate/examplecloud_test.go
- helper/resource/importstate/import_block_with_resource_identity_test.go
- helper/resource/plugin.go
- helper/resource/testing_new_import_state.go
The goal of the current assertion for identity imports is to ensure the prior saved identity is the same as the identity after import/refresh (i.e. the planned identity). This PR switches the previous logic from doing an apply, to using the `PlannedValues` of the no-op plan produced by a successful plannable import.
Luckily, `PlannedValues` also happens to be a `tfjson.StateValues`, similar to the `(tfjson.State).Values`, so there is a small refactor to do the comparison 👍🏻
> ResourceIdentity: Switch to using plan instead of applied state for asserting identity data

- .changes/unreleased/BUG FIXES-20250606-110444.yaml
- helper/resource/importstate/import_block_in_config_directory_test.go
- helper/resource/importstate/import_block_in_config_file_test.go
- helper/resource/importstate/import_command_with_id_test.go
- helper/resource/testing_new.go
- helper/resource/testing_new_import_state.go
Closes #516
Supersedes #519 
#516 was a regression split across two PRs so it was a little tough to catch, as well as the behavior of `teststep.Config` is not obvious:
- https://github.com/hashicorp/terraform-plugin-testing/pull/442
- Removed `teststep.Config` usage in favor of a string, however, the original `mergedConfig` is actually ignored when creating a new `teststep.Config`, which is confusing, but would essentially result in a `ConfigFile/Directory` test step being shaved down into just a string that has a `required_providers` block.
- https://github.com/hashicorp/terraform-plugin-testing/pull/494
- Removed the check for reusing a prior test step config, because it was checking a value that was always populated (either with real config via `step.Config` or just a shaved down …
> importstate: Fixed bug where prior test config is not used for `ConfigFile` or `ConfigDirectory`

- .changes/unreleased/NOTES-20250814-152742.yaml
- helper/resource/environment_variables.go
- helper/resource/plugin.go
- helper/resource/testing_new_config.go
Backports #496 into `release/1.13.x`
cc: @BBBmau
This change is intended to unlock an upgrade path from v1.5.1 to latest v1.13.1.
When "refresh after apply" is set to non-empty via an environment variable, a Config-mode test step will invoke a refresh before successful completion. This is intended as a compatibility measure for test cases that have different -- but semantically-equal -- state representations in their test steps. When comparing two states, the testing framework is not aware of semantic equality or set equality, as that would rely on provider logic.
A Config-mode test step that is followed by a Refresh-mode test step will not incur an extra refresh. This is a backward-compatible way for a provider to eventually remove the compatibility flag – existing tests can be updated …
> helper/resource: compatibility refresh after config mode test step (#496)
